spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://restaurante_postgres_container:5432/restaurant?useSSL=false
    password: postgres
  flyway:
    locations: classpath:db/migration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
springdoc:
  api-docs:
    enabled: 'true'
  swagger-ui:
    path: /swagger-ui.html
server:
  servlet:
    context-path: /restaurante