apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-pod
  template:
    metadata:
      name: api-pod
      labels:
        app: api-pod
    spec:
      containers:
        - name: api-restaurant-container
          image: samuelmolendolff/api-restaurant:1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-configmap
          livenessProbe:
            httpGet:
              port: 8080
              path: /restaurante/api/v1/produto
            periodSeconds: 10
            failureThreshold: 2
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "pg_isready -h svc-db -p 5432"
            initialDelaySeconds: 15
            periodSeconds: 10