apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restaurant
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres