apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  template:
    metadata:
      name: db-pod
      labels:
        app: db-pod
    spec:
      containers:
        - name: db-restaurant-container
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-configmap
  replicas: 3
  selector:
    matchLabels:
      app: db-pod