apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: db-pod
spec:
  containers:
    - name: db-restaurant-container
      image: postgres:15
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
            name: db-configmap