version: '3.7'
services:
  db:
    image: postgres:10
    container_name: postgres
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=GMT
    ports:
      - 5432:5432
    networks:
      - commons-api
  aplicacao:
    image: restaurante-aplicacao-web:1.0-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - commons-api


networks:
  commons-api:
    driver: bridge