version: '3.7'
services:
  db:
    image: postgres:10
    env_file:
      - db.env
    container_name: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=GMT
    ports:
      - 5432:5432
    networks:
      - commons-api
  aplicacao:
    image: restaurante-aplicacao-web:1.0-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - commons-api


networks:
  commons-api:
    driver: bridge